Fixes the asset import path if os dirs are empty
drwhut/tabletop-club pull request #125
Opened 2022-11-28 17:11 UTC by elmodor

**Fixes/Solves**
Fixes #109 

I moved the OS calls out of the for loop so they are done only once. If they are empty the replace will be done with "." instead resulting in `./TabletopClub/assets` as discussed in #109

Tested and worked for my issue. Should behave the same if OS calls are correct

2022-11-28 18:02 UTC, drwhut requested changes
Looks good! Just think the readability of a few lines can be improved.

2022-11-28 18:02 UTC, drwhut commented on game/Scripts/AssetDB.gd
> +	desktop_dir = desktop_dir if desktop_dir else "."
For readability, should probably make the conditions explicitly check if the strings are empty, e.g.
```
downloads_dir = downloads_dir if not downloads_dir.empty() else "."
```
or:
```
if downloads_dir.empty():
    downloads_dir = "."
```

2022-11-28 19:45 UTC, elmodor commented on game/Scripts/AssetDB.gd
> +	desktop_dir = desktop_dir if desktop_dir else "."
Well I'm not a fan of negated statements (if not) - usually staying positive is easier to read and can avoid mistakes.

So I opted in for your second proposal.

2022-11-29 09:52 UTC, drwhut approved these changes
Looks good, thank you!

2022-11-29 09:53 UTC, merged