added shuffle stack shortcut
drwhut/tabletop-club pull request #132
Opened 2022-11-29 08:41 UTC by RomanNovo

**Fixes/Solves**
Solved [Issue-111](https://github.com/drwhut/tabletop-club/issues/111)
#111 

For default key is Z

2022-11-29 10:32 UTC, drwhut requested changes
Thank you for the PR! I've just got a few points/questions:

- The shortcut should be able to be changed in the options menu, under "Key Bindings".
- In CameraController, we may want to account for the fact the player might be hovering one, or multiple, pieces. If multiple pieces are being hovered, do we allow the player to shuffle all the stacks being hovered, or none at all?
- Should we only allow stacks to be shuffled when they are selected, rather than if the player is just hovering the mouse over them?

2022-11-29 12:21 UTC, RomanNovo commented
1. Added
2. In original Tabletop (actually checked right now) Shuffling with multiple pieces selected shuffled them separatly.
3. Again, in original version, select stack is not required for shuffled. Hover is enough

2022-11-29 15:46 UTC, drwhut requested changes
Just a few changes needed for the options menu.

2022-11-29 15:46 UTC, drwhut commented on game/Scenes/OptionsMenu.tscn
> +visible = false
Should set the Audio tab to be visible again.

2022-11-29 15:46 UTC, drwhut commented on game/Scenes/OptionsMenu.tscn
> -visible = false
Should not be visible by default.

2022-11-29 15:46 UTC, drwhut commented on game/Scenes/OptionsMenu.tscn
> +[node name="ShuffleButton2" type="Button" parent="MarginContainer/VBoxContainer/TabContainer/Key Bindings/GridContainer"]
Is it ok if the button is called "ShuffleButton" rather than "ShuffleButton2"?

2022-11-29 15:46 UTC, drwhut commented on game/Scenes/OptionsMenu.tscn
> +hint_tooltip = "Flip the selected piece on the horizontal axis."
Need to update the tooltip.

2022-11-29 17:42 UTC, elmodor commented on game/Scripts/Game/CameraController.gd
> +	elif event.is_action_pressed("game_shuffle_stack", true):
Why is allow_echo set to `true` here?
As far as I understand the documentation, an echo is if the key is being held down. But why is it not set to true for moving the camera but it still works there when the key is being held down?
As far as I understand it other actions should be set to `true` as well?

2022-11-29 18:01 UTC, RomanNovo commented on game/Scripts/Game/CameraController.gd
> +	elif event.is_action_pressed("game_shuffle_stack", true):
it is satisfying. You can hold button to continuously shuffle the deck. It will become more pleasant, if add animations.

2022-11-29 18:12 UTC, elmodor commented on game/Scripts/Game/CameraController.gd
> +	elif event.is_action_pressed("game_shuffle_stack", true):
Oh yeah I can't wait to see the animation! :smile: 

I understood the logic of the event now.

2022-11-30 10:18 UTC, drwhut requested changes
Think the tooltip needs to be a little bit more descriptive.

2022-11-30 10:18 UTC, drwhut commented on game/Scenes/OptionsMenu.tscn
> +hint_tooltip = "Shuffle stack"
Is it ok if this is more descriptive? e.g. "Shuffle stacks of cards and tokens that are selected, or that the mouse is over."

2022-11-30 10:24 UTC, drwhut commented on game/Scripts/Game/CameraController.gd
> +	elif event.is_action_pressed("game_shuffle_stack", true):
I didn't spot this in my initial review - the potential problem here is that the client will send a request to shuffle the stack every time the event is triggered, and depending on the client's framerate, this can be up to 200 times a second, which is way too many.

If you want to keep the echo, I would suggest putting a timeout on the server side.

2022-11-30 12:53 UTC, RomanNovo commented on game/Scenes/OptionsMenu.tscn
> +hint_tooltip = "Shuffle stack"
Yea, sure

2022-11-30 21:24 UTC, drwhut reviewed
Thank you! I'll test it on my end before approving (including the echo, I need to check the server is not overloaded with requests).

2022-12-01 20:42 UTC, elmodor commented on game/Scripts/Game/CameraController.gd
> +		if _selected_pieces.empty():
Sorry for bringing this up so late, I was just looking into mouse over events.

Do we want to differentiate between selection and mouse over?
We were talking about this the other day in an issue and I looked into how "tabletop sim" solves this - they apply actions on all selected and mouse over objects.

If an object is being hovered by the mouse this usually means you want to interact with it as well. Same as selections.

Thoughts?

2022-12-02 11:52 UTC, drwhut commented on game/Scripts/Game/CameraController.gd
> +		if _selected_pieces.empty():
Personally if I've selected some objects, I would expect that *only* those objects would be "modified". But I think this is more of a subjective thing.

2022-12-02 13:36 UTC, drwhut commented
With the echo events, the client sends requests to the server around every 30ms, which is too fast in my opinion.

We can either:
- Keep detecting echo events, but add a timeout to `request_shuffle` on the server side (e.g. 500ms, or 1000ms?)
- Not detect echo events.

2022-12-02 20:07 UTC, RomanNovo commented
Screw this. Save idea for later. Will delete echo event

2022-12-03 12:54 UTC, drwhut approved these changes
Looks good, will test again before merging.

2022-12-03 13:05 UTC, merged