Dice: Multiple normals per face value
drwhut/tabletop-club pull request #308
Opened 2023-09-07 19:08 UTC by 20kdc

**Changes**

* face_values values can now be Vector2 *or* an array of Vector2. Internal representation is array of Vector3. Array mustn't be empty. The first vector will be used as the rotation when setting the value.
* Removed restriction on value count matching dice sides. (While the total amount of normals could be checked, IMO this restriction is arbitrary. Branch is on the way out anyway so any change that would really break/fix this will probably break everything anyway, see reference to #209 later.)

**Fixes/Solves**
*What does this PR fix or solve? If applicable, put the issue number here.*

![image](https://github.com/drwhut/tabletop-club/assets/22304167/15504bcb-ed9c-43a2-b241-6c5e3aee2b73)
This screenshot is an example use-case: Fudge/FATE dice. These have two blanks (value 0), two + (value 1) symbols and two - (value -1) symbols.
The way you calculate rolls with these is to roll four at once, then total the values. Tabletop Club almost supports this perfectly, but without this PR, their values cannot be properly represented (at least without perhaps tricks like int/float differentiation) and thus it's not possible to get a total.

```
face_values = {
    1: [Vector2(0.0, 0.0), Vector2(180.0, 0.0)],
    0: [Vector2(0.0, 90.0), Vector2(0.0, -90.0)],
    -1: [Vector2(-90.0, 0.0), Vector2(90.0, 0.0)]
}
```
This also partially helps #209 in regards to dice that have the same number repeated, *though a full solution including names is not provided.*

Since asset compatibility with past 0.1.x versions would ideally be maintained anyway, this doesn't change anything for anyone who wants to further that cause in the 0.1.x series; they'd have to implement translation in AssetDB no matter what, and the translation from a single normal to an array is trivial. They do have slightly less to do in that they no longer need to implement the checking of multiple normals for a value, as that's now the canonical state.

_**NOTE:** Make sure this PR goes to the `master` branch! If this fix applies to
previously released versions, then the commits will be cherry-picked afterwards._
Done.

2023-09-08 10:50 UTC, drwhut commented
Thank you for the PR! 🥳 

My only concern with it's current implementation is that it would not be compatible with the new face-value system in v0.2.0 (which has already been implemented and tested in the `0.2-rewrite` branch, see [here](https://github.com/drwhut/tabletop-club/blob/664781ab62d4a6d882e3eda67e70c9c51c02a633/game/assets/asset_pack_type_catalog.gd#L570C3-L570C3) for how the game reads the `config.cfg` file on that branch).

For reference, the format for the `face_values` property in v0.2.0 is essentially reversed from what it is in v0.1.x, in that the keys are the rotation required to make the given face point upwards, and the value is the, well, value:
```ini
; An example 'face_values' from v0.2.0:
face_values = {
    Vector2(0.0, 0.0): null,
    Vector2(90.0, 0.0): 2,
    Vector2(0.0, 90.0): 4.5,
    Vector2(180.0, 0.0): "wat",
}
```

I did it this way for two reasons: 1. it solved the duplicate face-value problem, as only the keys are required to be unique, and 2. I figured it is incredibly unlikely that anyone would want two separate values for one face.

I've also made it so that in v0.2.0, the game will still accept the current format for backwards-compatibility, but it will show a warning saying the new format should be used instead.

So yeah to prevent incompatibilites between versions, either the v0.2.0 system will need to be backported, or the v0.2.0 system will need to be replaced with this PR's system.

2023-09-08 11:16 UTC, 20kdc commented
I'll go with backporting the v0.2.0 system, now I know what that looks like

2023-09-08 12:45 UTC, 20kdc commented
Hopefully this *should* be compatible?

2023-09-09 04:35 UTC, drwhut requested changes
Looks good! I've just got a few points that need addressing, but once they're resolved I'll test the changes on my end and merge if I can't find anything else :+1:

2023-09-09 04:35 UTC, drwhut commented on docs/custom_assets/asset_packs/asset_types.rst
> +If the same value needs to be present on multiple faces, a list may be specified rather than a single Vector2, as so:  ``-1: [Vector2(0.0, 0.0), Vector2(180.0, 0.0)]``
The docs will need to be updated with the new changes.

2023-09-09 04:35 UTC, drwhut commented on game/Scripts/AssetDB.gd
> -				num_faces = 20
I'm not so sure if the game should just ignore the number of faces - at the very least, I think the game could show a warning if the number of assigned values does not match, that way the creator can spot the "error" and correct it.

2023-09-09 04:35 UTC, drwhut commented on game/Scripts/AssetDB.gd
> +						fv_value = str(value)
Think it's worth having some type-checking for the value, just to close up any potential exploits. For reference, in v0.2.0 the valid data types are Null, Integers, Floats, and Strings.

2023-09-09 10:36 UTC, 20kdc commented on game/Scripts/AssetDB.gd
> -				num_faces = 20
The number of assigned values doesn't really make sense due to faces with the same value. Total normal count would probably work.

2023-09-09 10:56 UTC, 20kdc commented on game/Scripts/AssetDB.gd
> -				num_faces = 20
Implemented as a warning based on total normal count.

2023-09-09 10:56 UTC, 20kdc commented on game/Scripts/AssetDB.gd
> +						fv_value = str(value)
Added, see f74d4d8

2023-09-09 10:57 UTC, 20kdc commented on docs/custom_assets/asset_packs/asset_types.rst
> +If the same value needs to be present on multiple faces, a list may be specified rather than a single Vector2, as so:  ``-1: [Vector2(0.0, 0.0), Vector2(180.0, 0.0)]``
Oops, probably lost it during the staging process... added in f74d4d8

2023-09-10 08:49 UTC, drwhut approved these changes
Looks good, thank you! Will test as soon as I can before merging :+1:

2023-09-17 13:19 UTC, merged

2023-09-17 14:31 UTC, 20kdc commented
Ah, thank you

2023-09-17 14:32 UTC, drwhut commented
No, thank YOU! :grin: