added an undo button
drwhut/tabletop-club pull request #60
Opened 2021-06-22 13:23 UTC by SeanKuehl

**Fixes/Solves**
Add an undo button. issue #29

I have added an undo button that will restore a previous save state. Right now save states happen in three events: piece added, piece removed and table flipped. These events are also on timers, so after they create a save state they will have to wait out several calls before they can create a save state again.

2021-06-22 15:32 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +var _srv_remove_piece_timer_max: int = 5
A couple of things here:
- Personally, I think instead of having an undo state being added e.g. every 5 pieces, I think there should be a 'cooldown' whenever a piece is added. For example, someone creates a piece, which sets a cooldown for 10 seconds. If someone adds another piece in that 10 seconds, the cooldown is reset back to 10 seconds. Only after the 10 seconds is an undo state created when a piece is added. Let me know what you think about this idea!
- I think instead of having variables for each event, have a dictionary where the keys are the events, and the values are the timers. This way, there aren't as many variables, and more events could easily be added.

2021-06-22 15:34 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +master func push_undo_state() -> void:
`push_undo_state` should not be `master` - only the host dictates when an undo state is pushed onto the stack, and plus, a malicious player could spam remote calls to this function as well.

2021-06-22 15:35 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +		print(_srv_add_piece_timer)
Should this not come before the piece is added to the scene tree?

2021-06-22 15:37 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +		rpc_id(1, "push_undo_state")	#make host add an undo state
This function is called by the host on every player's machine, meaning that this `rpc_id` will be called for every player, making as many undo states as there are players.

As alluded to above as well, I don't think non-host players should have the ability to push onto the undo stack either.

Instead you could check to see if the function is being run on the host machine with `get_tree().is_network_server()`, and only if that returns true, run the `push_undo_state` function.

2021-06-23 10:53 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +master func push_undo_state() -> void:
When I did not have the function as master I had errors, is there another keyword like master that would work?

2021-06-23 13:30 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +		print(_srv_add_piece_timer)
Moved it to the top of the add_piece function

2021-06-23 13:57 UTC, SeanKuehl commented on game/Scripts/Game/CameraController.gd
> +	room.rpc_id(1, "pop_undo_state")	#make the host pop an und state
Hey, I set it up to do the signal but when I try to connect the signal in room it says I'm trying to connect a nonexistent signal. How did you get the other signals to work between scripts?

2021-06-23 14:00 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +		rpc_id(1, "push_undo_state")	#make host add an undo state
I've added get_tree().is_network_server() as the third requirement in the if statements.

2021-06-23 14:46 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +var _srv_remove_piece_timer_max: int = 5
I have implemented the dictionary and it is now time based(rough amounts of time based on physics process "ticks").

2021-06-23 14:54 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +		_srv_remove_piece_timer -= 1
I've added get_tree().is_network_server() as the third requirement in the if statements.

2021-06-23 15:35 UTC, drwhut commented
I can see that you've replied to my comments, but I can't see the changes you've made - you'll need to commit and push the changes you've made to your fork's branch.

2021-06-23 20:06 UTC, SeanKuehl commented
Hey, I have since committed the changes I was able to make. As mentioned in the comments, I have implemented the dictionary system and switched the timers to a 'real time' approach. I also made it so that only the host will save undo states upon events. I do however have some questions about the signal method and the master keyword, hence why these changes have not yet been made.

2021-06-23 20:30 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +master func push_undo_state() -> void:
Instead of trying to call the function remotely, call it locally (i.e. just call `push_undo_state()`), but make sure that only the host calls it with `get_tree().is_network_server()`.

2021-06-23 20:34 UTC, drwhut commented on game/Scripts/Game/CameraController.gd
> +	room.rpc_id(1, "pop_undo_state")	#make the host pop an und state
Using the editor, you can follow these steps to connect signals:
1. Go to the scene that contains both nodes that you want to connect (in this case, the camera controller and the room).
2. Click on the node that broadcasts the signal (the camera controller), and on the top right, click `Node`, which should show you the signals.
3. Double-click the new signal, and "attatch" it to the room node. This should create a new function in that node's script that is called when the signal is fired.

2021-06-23 20:41 UTC, drwhut requested changes
Great stuff! The remaining comments are just nit-picky things.

2021-06-23 20:41 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +
I would put this after the `if get_tree().get_rpc_sender_id() != 1:` line for security reasons (what is a malicious player spams remote calls to this function?).

2021-06-23 20:41 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +			_srv_undo_state_events[key] -= 1
I would use the `delta` value instead of decrementing integers here, just so the timer is accurate.

2021-06-23 20:41 UTC, drwhut commented on game/Scripts/Game/CameraController.gd
> +	#emit_signal("popping_undo_state")
This line is correct! It should work once you've connected the signal to the `Room` node via the editor.

2021-06-23 22:32 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +master func push_undo_state() -> void:
Thank you, I have removed the master keywords and added this check instead to the function called by the undo button's signal.

2021-06-23 22:33 UTC, SeanKuehl commented on game/Scripts/Game/CameraController.gd
> +	room.rpc_id(1, "pop_undo_state")	#make the host pop an und state
Thank you, I've hooked up the signal and it works.

2021-06-23 22:34 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +
I have moved the code handling the add_piece event below that if statement

2021-06-23 22:38 UTC, SeanKuehl commented on game/Scripts/Game/CameraController.gd
> +	#emit_signal("popping_undo_state")
Yes, now that I have connected the signals it works. Thank you.

2021-06-23 22:42 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +			_srv_undo_state_events[key] -= 1
I have made this change. Only note is that it seems that the delta value is much lower than one and the timer length will have to be adjusted. I'll adjust the timer lengths to be reasonable and commit my changes soon.

2021-06-24 00:13 UTC, drwhut requested changes
Awesome! One last thing regarding the `master` keyword in `pop_undo_state()`, have a look at the comment.

2021-06-24 00:13 UTC, drwhut commented on game/Scripts/Game/3D/Room.gd
> +func pop_undo_state() -> void:
Sorry, I just meant remove the `master` keyword from `push_undo_state()` - any player should be able to undo the game state, but only the host should decide when an undo state is pushed onto the stack.

2021-06-24 10:57 UTC, SeanKuehl commented on game/Scripts/Game/3D/Room.gd
> +func pop_undo_state() -> void:
Thanks for clearing that up. I re-added the keyword, changed the call for pop back to rpc_id(1, "pop_undo_state") but removed the code that only let the host do it. Now anyone pressing the undo button can undo, but only the host adds states.

2021-06-24 15:27 UTC, drwhut approved these changes

2021-06-24 15:31 UTC, drwhut commented
Great! I'll test the branch further later today before I merge it into master. :smile:

2021-06-25 00:15 UTC, drwhut commented
I've been trying out the branch, and I've come across a potential issue (not a bug per se, but rather a design issue): If you repeat flipping the table, then undoing, quickly enough then there comes a point where you cannot undo, and you cannot get the table back without pressing the "reset table" button. This is due to the fact that the second undo state isn't created because of the 10-second rule.

The reason we introduced the 10-second rule was because of the possibility of players spamming new objects into the game, with each one creating a new undo state - however, I think every table flip should create a new undo state, purely because it is such a 'major' event compared to adding an object.

Maybe we could have it so that there's a constant dictionary of 'timings' for each event, where adding a piece is 10 seconds (as before), removing a piece might be something like 5 seconds, and flipping the table would effectively be 0 seconds. What do you think?

2021-06-25 11:51 UTC, SeanKuehl commented
Make another dictionary with the same keys "add_piece" but instead the value is what the timer is set to? So for add_piece it would be 10, but then for flip_table it could be 0, I can do that, it should take very long since I'm just replacing the number the timer is set with with the value in a dictionary. I'll also make the timing changes you made in the post.

2021-06-27 04:37 UTC, merged

2021-06-27 04:38 UTC, drwhut commented
Sorry for the late response, I was gonna check the new commit yesterday, but I ended up getting my first COVID vaccine (yay!) and it wiped me out for the rest of the day.

Thank you so much for contributing to the project! :smile: